# Hands-On Practice: Linear Algebra for AI

## Exercise 1: Working with Scalars and Vectors

In [ ]:
import numpy as np

#Creating a scaler
scaler = 9
print(scaler)

#Creating a Vector
vector = np.array([1,2,3])
print(vector)

#Scaling vector with a scaler aka. scaled vector
scaled_vector = scaler * vector
print(scaled_vector)
# Task 1: Create a vector [4, 5, 6] and multiply it by a scalar of 3. Print the result.

9
[1 2 3]
[ 9 18 27]


## VECTOR ADDITION AND SUBTRACTION

In [ ]:
# Task 2: Create two vectors [10, 20] and [5, 15]. Compute and print their sum
# and difference.

## MATRIX CREATION AND SIMPLE OPERATION

In [ ]:
matrix1 = np.array([[1,2],[4,5]])
matrix2 = np.array([[3,6],[8,9]])

print(matrix1)
print(matrix2)

## Task 3: Create two 2x2 matrices [[2, 3], [4, 5]] and [[1, 1], [2, 2]]. Compute and
# print their sum.

[[1 2]
 [4 5]]
[[3 6]
 [8 9]]


## MATRIX MULTIPLICATION

In [ ]:
matrix1 = np.array([[2,4],[5,7]])
matrix2 = np.array([[6,8],[9,11]])

product = np.dot(matrix1,matrix2)
print(product)

# Task 4: Create two 2x2 matrices [[1, 0], [0, 1]] and [[2, 3], [4, 5]]. Compute and
# print their product.

In [ ]:
matrix1 = np.array([[1, 2], [3, 14]])
matrix2 = np.array([[15, 6], [7, 8]])

mat_mul_index1 = matrix1[0,0] * matrix2[0,0] + matrix1[0,1] * matrix2[1,0]
mat_mul_index2 = matrix1[0,0] * matrix2[0,1] + matrix1[0,1] * matrix2[1,1]
mat_mul_index3 = matrix1[1,0] * matrix2[0,0] + matrix1[1,1] * matrix2[1,0]
mat_mul_index4 = matrix1[1,0] * matrix2[0,1] + matrix1[1,1] * matrix2[1,1]

print(mat_mul_index1, mat_mul_index2, mat_mul_index3, mat_mul_index4)


mat = np.dot(matrix1, matrix2)
print(mat)



# A more simplified approach!!!!!!!!!!!

a, b = matrix1[0]
c, d = matrix1[1]
e, f = matrix2[0]
g, h = matrix2[1]

mat_mul_index1 = a * e + b * g
mat_mul_index2 = a * f + b * h
mat_mul_index3 = c * e + d * g
mat_mul_index4 = c * f + d * h

print(mat_mul_index1, mat_mul_index2)
print(mat_mul_index3, mat_mul_index4)

## Exercise 5: Identity Matrix and Transpose

In [ ]:
identity = np.eye(2,dtype=int)
print(identity)


matrix1 = np.array([[2,4],[5,7]])
print(matrix1.T)

# Task 5: Create a 2x3 matrix [[10, 20, 30], [40, 50, 60]]. Compute and print its
# transpose. Also, create and print a 2x2 identity matrix.

[[1 0]
 [0 1]]
[[2 5]
 [4 7]]


## MATRIX INVERSE

In [ ]:
matrix1 = np.array([[2,4],[5,7]])
inverse = np.linalg.inv(matrix1)

identity = np.dot(matrix1,inverse)
print(identity)

[[1.0000000e+00 0.0000000e+00]
 [4.4408921e-16 1.0000000e+00]]
