#Day 2 Week 2 Tasks as Homework


In [2]:
#Task using manual multiplication method
import numpy as np
matA=np.array([[1,2],[3,4]])
matB=np.array([[5,6],[7,8]])
ind00=matA[0,0]*matB[0,0]+matA[0,1]*matB[1,0]
ind01=matA[0,0]*matB[0,1]+matA[0,1]*matB[1,1]
ind10=matA[1,0]*matB[0,0]+matA[1,1]*matB[1,0]
ind11=matA[1,0]*matB[0,1]+matA[1,1]*matB[1,1]
mat_mult=np.array([[ind00,ind01],[ind10,ind11]])
print(mat_mult)
actualmat=np.dot(matA,matB)
print(actualmat)


[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [3]:
#Task1
vct=np.array([7,8,9])
sc=2
print(sc*vct)

[14 16 18]


In [4]:
#Task2
vct1=np.array([3,4])
vct2=np.array([1,2])
sum1=vct1+vct2
diff1=vct1-vct2
print(sum1)
print(diff1)

[4 6]
[2 2]


In [5]:
#Task3
mat1=np.array([[0,1],[2,3]])
mat2=np.array([[4,5],[6,7]])
sum2=mat1+mat2
print(sum2)

[[ 4  6]
 [ 8 10]]


In [6]:
#Task4
m1=np.array([[2,1],[0,3]])
m2=np.array([[1,2],[3,4]])
dot=np.dot(m1,m2)
print(dot)

[[ 5  8]
 [ 9 12]]


In [7]:
# Task 5: Create a 2x3 matrix [[10, 20, 30], [40, 50, 60]]. Compute and print its
# transpose. Also, create and print a 2x2 identity matrix.
newmat=np.array([[5,10,15],[20,25,30]])
transpose=newmat.T
print(transpose)
identity=np.identity(2,dtype=int)
print(identity)

[[ 5 20]
 [10 25]
 [15 30]]
[[1 0]
 [0 1]]
