# NUMPY BASICS#

Creating a Numpy Array and its Attributes

In [ ]:
#importing numpy library
import numpy as np
#creating a list
my_list = [1,2,3,4,5]
#changing the list into a numpy array
my_array = np.array(my_list)
#printing the array
print(my_array)

#changing the list into a 1D numpy array
my_array=np.array([1,2,3,4,5])
print(my_array)

#creating a 0-D numpy array
zero_array= np.array(42)
#printing the 0-D numpy array
print(zero_array)

#Instead of creating a list on a separate variable we can directly pass it to .array() function
my_array=np.array([1,2,3,4,5])
print(my_array)

#creating a 2d array
two_d_array=np.array([[1,2,3],[4,5,6]])
print(two_d_array)

#lets create a 3d array now
three_d_array=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
#printing the 3d array
print(three_d_array)

In [ ]:
#lets create an array and see its attributes
import numpy as np
my_array=np.array([[1,2,3],[4,5,6]])
print(my_array) #printing the array
print(my_array.ndim) #printing the dimension of the array
print(my_array.shape) #printing the shape of the array
print(my_array.dtype) #printing the type of the array
print(my_array.size) #printing the size of the array

[[1 2 3]
 [4 5 6]]
2
(2, 3)
int64
6


ACCESSING AND MANIPULATING ARRAY ELEMENTS

In [ ]:
#lets create a 1D array and print one of its elements
one_arr=np.array([1,2,3,4,5,6])
print(one_arr[4])

#lets print using negative indexing
print(one_arr[-3])



5
4


In [ ]:
import numpy as np
#lets do for a 2d array
two_arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(two_arr[0,2])

3


In [ ]:
import numpy as np
#lets move to 3d array
three_arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(three_arr[1,0,0])
print(three_arr[-1,-2,-1]) #negative indexing

7
9


#Slicing Arrays#

Some Important Slicing Concepts


array[start:end]


array[start:end:steps]

In [ ]:
# slicing an array from 0th index to 8th index
import numpy as np
my_array=np.array([1,2,3,4,5,6,7,8,9,10])
print(my_array[0:8])

[1 2 3 4 5 6 7 8]


In [ ]:
# slicing an array with steps
import numpy as np
my_new_array=np.array([1,2,3,4,5,6,7,8,9,10])
print(my_new_array[0:8:2])

[1 3 5 7]


In [ ]:
#Slicing on a 2D array
import numpy as np
my_two_d=np.array([[1,2,3,4,5,6,7,8,9],[10,11,12,13,14,15,16,17,18]])
print(my_two_d[1,0:6])
print(my_two_d[0,3:6])


[10 11 12 13 14 15]
[4 5 6]


In [ ]:
import numpy as np
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [3]:
import numpy as np
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [1]:
import numpy as np
my_list=[7,14,21,28]
my_array=np.array(my_list)
print(my_array)


[ 7 14 21 28]


In [2]:
import numpy as np
two_d_array=np.array([[5,10,15],[20,25,30]])
print(two_d_array.ndim)
print(two_d_array.shape)


2
(2, 3)


In [8]:
import numpy as np
zeros=np.zeros([2,3])
my_array=np.arange(0,13,3)
print(zeros)
print(my_array)

[[0. 0. 0.]
 [0. 0. 0.]]
[ 0  3  6  9 12]


In [6]:
import numpy as np
my_array=np.array([2,4,6,8])
print(3*my_array)

[ 6 12 18 24]


In [7]:
import numpy as np
my_array=np.array([1,3,5,7,9,11])
print(my_array[2])
print(my_array[1:4])

5
[3 5 7]
