In [ ]:
import numpy as np
my_array=np.random.randint(1,10,size=(3,3))
print(my_array)
my_array[my_array>5]=0
print(my_array)

[[6 5 4]
 [7 3 3]
 [1 7 5]]
[[0 5 4]
 [0 3 3]
 [1 0 5]]


In [ ]:
import numpy as np
first_array=np.array([2,4,6,8])
sec_array=np.array([1,3,5,7])
result=first_array+sec_array
dot_product=np.dot(first_array,sec_array)
print(result)
print(dot_product)


[ 3  7 11 15]
100


In [ ]:
import numpy as np
ones=np.ones([4,3])
print(ones)
one_d_array=np.array([10,20,30])
result_array=np.add(ones,one_d_array)
print(result_array)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[11. 21. 31.]
 [11. 21. 31.]
 [11. 21. 31.]
 [11. 21. 31.]]


In [4]:
import numpy as np
my_array=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(my_array)
second_column = my_array[:, 1]
print(second_column)
col2_mean = np.mean(second_column)
print(col2_mean)
reshaped_array=my_array.reshape(-1)
print(reshaped_array)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2 5 8]
5.0
[1 2 3 4 5 6 7 8 9]


In [8]:
import numpy as np
one_d=np.array([10,20,30,40,50,60])
print(one_d)
one_d[one_d>30]=one_d[one_d>30]**2
print(one_d)

[10 20 30 40 50 60]
[  10   20   30 1600 2500 3600]


In [ ]:
import numpy as np
one_d=np.arange(2,11,step=2)
print(one_d)
result=one_d+5
print(result)

[ 2  4  6  8 10]
[ 7  9 11 13 15]


In [ ]:
import numpy as np
two_d=np.array([[1,3,5],[2,4,6]])
result= two_d[0]
print(result)
print(np.sum(result))

[1 3 5]
9
